### ISSUE TITLE
Python 2-3 compatibility

### ISSUE THREAD

**Issue by aldro61** [aldro61/pyscm#22]
Make the new code Python 2-3 compatible. 

I'm not sure if the way of compiling external modules has changed in Python 3. There might be minor changes to make to the bindings. You'll see if it breaks hehe :)

**Comment by PhrankBrochu** [comment]
Usual imports for python2-3 compatibility have been added to the files. All works well in Python2.

When it comes to python 3, the cpp extensions will not compile, with the same error message in two environments.

"building 'pyscm._scm_utility' extension
/software6/compilers/gcc/5.4/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/fbrochu/Py3fbrochu/include -I/software6/apps/python/3.5.0/include/python3.5m -I/home/fbrochu/Py3fbrochu/lib/python3.5/site-packages/numpy/core/include -c cpp_extensions/utility_python_bindings.cpp -o build/temp.linux-x86_64-3.5/cpp_extensions/utility_python_bindings.o -std=c++0x
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/fbrochu/Py3fbrochu/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/fbrochu/Py3fbrochu/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/fbrochu/Py3fbrochu/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpp_extensions/utility_python_bindings.cpp:2:
/home/fbrochu/Py3fbrochu/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
cpp_extensions/utility_python_bindings.cpp: In function ‘PyObject* init_scm_utility()’:
cpp_extensions/utility_python_bindings.cpp:186:48: error: ‘Py_InitModule’ was not declared in this scope
     (void)Py_InitModule("_scm_utility", Methods);
                                                ^
cpp_extensions/utility_python_bindings.cpp:188:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
error: command '/software6/compilers/gcc/5.4/bin/gcc' failed with exit status 1"

Will investigate into issue. Seems to be an issue with cpp extensions changing between py2 and py3?

**Comment by PhrankBrochu** [comment]
Problem fixed in commit 249a7fd5f5db7dbe2ac5f0fed6af09b7609c80c7
