### ISSUE TITLE
Scikit-learn compatibility

### ISSUE THREAD

**Issue by aldro61** [aldro61/pyscm#25]
Ensure that we are 100% scikit-learn compatible. I think I did everything that is required.

Try to test with GridSearchCV and Pipeline.

Guidelines [here](http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator)

**Comment by dizam92** [comment]
1. First i got this error: 

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-31-0e75b92ebdd8> in <module>()
> ----> 1 gs_clf.fit(X=X, y=y)

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.pyc in fit(self, X, y, groups)
>     943             train/test set.
 >    944         """
> --> 945         return self._fit(X, y, groups, ParameterGrid(self.param_grid))
   >  946 
   >  947 
> 
> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.pyc in _fit(self, > X, y, groups, parameter_iterable)
 >    562                                   return_times=True, return_parameters=True,
 >    563                                   error_score=self.error_score)
> --> 564           for parameters in parameter_iterable
>     565           for train, test in cv_iter)
>     566 
> 
> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.pyc in > > __call__(self, iterable)
>     756             # was dispatched. In particular this covers the edge
 >    757             # case of Parallel used with an exhausted iterator.
> --> 758             while self.dispatch_one_batch(iterator):
>     759                 self._iterating = True
>     760             else:

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.pyc in dispatch_one_batch(self, iterator)
>     606                 return False
>     607             else:
> --> 608                 self._dispatch(tasks)
>     609                 return True
 >    610 

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.pyc in _dispatch(self, batch)
>     569         dispatch_timestamp = time.time()
>     570         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
> --> 571         job = self._backend.apply_async(batch, callback=cb)
>     572         self._jobs.append(job)
 >    573 

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.pyc in apply_async(self, func, callback)
>     107     def apply_async(self, func, callback=None):
>     108         """Schedule a func to be run"""
> --> 109         result = ImmediateResult(func)
>     110         if callback:
>     111             callback(result)

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.pyc in __init__(self, batch)
 >    324         # Don't delay the application, to avoid keeping the input
>     325         # arguments in memory
> --> 326         self.results = batch()
>     327 
>     328     def get(self):

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.pyc in __call__(self)
>     129 
>     130     def __call__(self):
> --> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
>     132 
 >    133     def __len__(self):

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.pyc in > _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, error_score)
 >    225 
>     226     if parameters is not None:
> --> 227         estimator.set_params(**parameters)
 >    228 
>     229     start_time = time.time()

> /home/maoss2/PycharmProjects/pyscm/pyscm/scm.py in set_params(self, **parameters)
>      52         self.random_state = np.random.RandomState(random_state) if random_state is not None \
>      53             else np.random.RandomState(42)
> ---> 54 
>      55     def get_params(self, deep=True):
 >     56         return {"p": self.p, "model_type": self.model_type, "max_rules": self.max_rules,

> **AttributeError: 'SetCoveringMachineClassifier' object has no attribute 'setattr'**

So i made this patch for working around: 
`    def set_params(self, **parameters): `
 `        for parameter, value in parameters.items():`
   `          if parameter == 'p':`
  `               self.p = value`
   `          if parameter == 'model_type':`
   `              self.model_type = value`
   `          if parameter == 'max_rules':`
   `              self.max_rules = value`
   `          if parameter == 'random_state':`
   `              self.random_state = value`
   `      return self`

2-. Then i got this: 

> <ipython-input-5-0e75b92ebdd8> in <module>()
> ----> 1 gs_clf.fit(X=X, y=y)

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.pyc in fit(self, X, y, groups)
>     943             train/test set.
>     944         """
> --> 945         return self._fit(X, y, groups, ParameterGrid(self.param_grid))
>     946 
>     947 

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.pyc in _fit(self, X, y, groups, parameter_iterable)
>     548                                      n_candidates * n_splits))
>     549 
> --> 550         base_estimator = clone(self.estimator)
>     551         pre_dispatch = self.pre_dispatch
>     552 

> /home/maoss2/anaconda2/lib/python2.7/site-packages/sklearn/base.pyc in clone(estimator, safe)
 >     68     for name, param in six.iteritems(new_object_params):
>      69         new_object_params[name] = clone(param, safe=False)
> ---> 70     new_object = klass(**new_object_params)
>      71     params_set = new_object.get_params(deep=False)
>      72 

> /home/maoss2/PycharmProjects/pyscm/pyscm/scm.pyc in __init__(self, p, model_type, max_rules, random_state)
>      44         self.model_type = model_type
>      45         self.max_rules = max_rules
> ---> 46         self.random_state = np.random.RandomState(random_state) if random_state is not None \
>      47             else np.random.RandomState(42)
>      48 

> mtrand.pyx in mtrand.RandomState.__init__ (numpy/random/mtrand/mtrand.c:12670)()

> mtrand.pyx in mtrand.RandomState.seed (numpy/random/mtrand/mtrand.c:13350)()

> TypeError: Cannot cast array from dtype('O') to dtype('int64') according to the rule 'safe'
**No solution found yet**

**Comment by aldro61** [comment]
A random state is not a random seed. See previous comments.

**Comment by aldro61** [comment]
For the setattr error, simply replace by setattr(self, parameter, value).

**Comment by dizam92** [comment]
self.setattr(self, parameter, value)
AttributeError: 'SetCoveringMachineClassifier' object has no attribute 'setattr' 
But **setattr(self, parameter, value)** (without the first self.) works

**Comment by aldro61** [comment]
Where did you make this modification? Did you start a new branch for it? If so, coordinate with @PhrankBrochu so that you work in the same branch, since he has assigned himself to this issue.

**Comment by dizam92** [comment]
Nowhere yet, i'll talk to him to let him know when i'll do it.

**Comment by PhrankBrochu** [comment]
I can confirm that the fit worked while in a pipeline of the form: Pipeline([("scaler",StandardScaler()),("scm",SetCoveringMachineClassifier())])

I'll run the scm by sklearn.utils.estimator_checks to make sure.

**Comment by PhrankBrochu** [comment]
Can't make pyscm pass all checks in estimator_checks... but it seems to try to throw multiclass/multioutput problems at the scm which makes it crash.

Added a minor fix to the random_state in the branch, which seems a little more kosher and in line with sklearn code, but has no real impact on performance AFAIK.

**Comment by PhrankBrochu** [comment]
Traceback (most recent call last):
  File "sklearn_compatibility.py", line 28, in <module>
    grid.fit(X,y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 564, in _fit
    for parameters in parameter_iterable
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 768, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 719, in retrieve
    raise exception
pickle.PicklingError: Can't pickle <type 'instancemethod'>: it's not found as __builtin__.instancemethod


This happens in python2, while there is no problem in python 3... Only happens when the n_jobs of GridSearchCV != 1.

**Comment by aldro61** [comment]
@PhrankBrochu which modification to the random state are you talking about? You can create a pull request for your branch so that I'll be able to see all your commits as they come in. Also, please make sure that your branch is up to date with master, since @dizam92 changed how the random state worked yesterday.

**Comment by plpla** [comment]
The `GridSearchCV` function is still raising an exception when n_job > 1.

**Comment by aldro61** [comment]
Fully adressed in PR #36. We are not 100% compatible, since we don't support multiclass learning, but it's good enough for our current needs.

If we run into compatibility problems:
1) Create an issue
2) Add a test that reproduces the error
3) Patch the code
4) Pull request if the new test passes
