### ISSUE TITLE
Validate implementation complexity

### ISSUE THREAD

**Issue by aldro61** [aldro61/pyscm#26]
Extend the training_time.py example script to also plot the time while varying the number of examples. We should see that the time increases linearly with the number of examples and features.

Note: this is already done for features.

**Comment by dizam92** [comment]
Update: Code of training_time refactored. I made 2 functions. 

- increase_n_features() witch is the code before aiming to test the complexity while increasing the features space
- increase_n_examples() witch is the code before aiming to test the complexity while increasing the examples space

**Comment by dizam92** [comment]
@aldro61 This issue shouldn't be closed?

**Comment by aldro61** [comment]
## Linear with respect to the number of examples
![n_examples](https://cloud.githubusercontent.com/assets/2374980/24677671/92530b76-1955-11e7-98ab-4b0367f2324a.png)

## Linear with respect to the number of features
![n_features](https://cloud.githubusercontent.com/assets/2374980/24678269/ddc1fa16-1957-11e7-89dc-09958ec7baf9.png)

Looks pretty linear to me!
